steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/chatwoot-rt-bridge:$SHORT_SHA
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/chatwoot-rt-bridge:latest
      - -f
      - bridge/Dockerfile
      - .
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/chatwoot-rt-bridge:$SHORT_SHA
  - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/chatwoot-rt-bridge:latest
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
timeout: 2400s
