class Webhooks::WapiController < ActionController::API
  before_action :ensure_valid_channel

  # Achado real 24/08/2026 (produto-09): o corpo real do WAPI é
  # Content-Type application/json de verdade (confirmado com log temporário,
  # já removido -- tinha texto de mensagem real de cliente, não é pra ficar
  # em produção). O formato real: `{event, instanceId, isGroup, fromMe,
  # chat: {id}, sender: {id, senderLid, pushName}, messageId,
  # msgContent: {conversation}}` -- nada parecido com os paths especulativos
  # que `Wapi::PayloadNormalizer` tinha antes (corrigidos no mesmo achado).
  def process_payload
    Webhooks::WapiEventsJob.perform_later(project_id: params[:project_id], params: corpo_normalizado)
    head :ok
  end

  private

  # Se o Rails não reconheceu o Content-Type como JSON, `params` só tem o
  # que veio na URL -- tenta decodificar o corpo bruto como JSON na mão
  # antes de desistir, em vez de silenciosamente processar um payload
  # vazio (era exatamente esse silêncio que escondia o bug).
  def corpo_normalizado
    base = params.to_unsafe_hash
    campos_extras = base.keys - %w[project_id verify_token controller action]
    return base if campos_extras.any?

    begin
      JSON.parse(request.raw_post).merge(base)
    rescue JSON::ParserError
      base
    end
  end

  def ensure_valid_channel
    head :not_found and return unless channel

    # Same verify-token pattern as Channel::Whatsapp / Channel::Line: the token
    # is generated by us and shown in the callback URL config screen, provider
    # is expected to echo it back (query param or header) on every delivery.
    head :unauthorized and return unless valid_token?
  end

  def channel
    @channel ||= Channel::Wapi.find_by(project_id: params[:project_id])
  end

  def valid_token?
    provided = params[:verify_token] || request.headers['X-Wapi-Verify-Token']
    provided.present? && ActiveSupport::SecurityUtils.secure_compare(provided.to_s, channel.webhook_verify_token)
  end
end
