class Webhooks::WapiController < ActionController::API
  before_action :ensure_valid_channel

  def process_payload
    Webhooks::WapiEventsJob.perform_later(project_id: params[:project_id], params: params.to_unsafe_hash)
    head :ok
  end

  private

  def ensure_valid_channel
    head :not_found and return unless channel

    # Same verify-token pattern as Channel::Whatsapp / Channel::Line: the token
    # is generated by us and shown in the callback URL config screen, provider
    # is expected to echo it back (query param or header) on every delivery.
    head :unauthorized and return unless valid_token?
  end

  def channel
    @channel ||= Channel::Wapi.find_by(project_id: params[:project_id])
  end

  def valid_token?
    provided = params[:verify_token] || request.headers['X-Wapi-Verify-Token']
    provided.present? && ActiveSupport::SecurityUtils.secure_compare(provided.to_s, channel.webhook_verify_token)
  end
end
